- hosts: [debian]
  become: yes
  become_user: ansible
  tasks:
    - name: Update servers
      apt: update_cache=yes
    - name: Upgrade all 
      apt: upgrade="dist-upgrade" autoclean=yes autoremove=yes
