---

- hosts: [debian]
  become: yes
  tasks:
  - name: Update servers
    apt: update_cache=yes
    until: result is not failed
  - name: Upgrade all 
    apt: upgrade=dist autoclean=yes autoremove=yes
    async: 1000
